pre_run: []
run_action: []
post_run: []

runner_config:
  tmp_dir: "/tmp/ansible_runner"   # ğŸ—‚ï¸ DiretÃ³rio temporÃ¡rio para logs
  parallel: false                  # âš¡ Rodar comandos em paralelo
  retries: 0                       # ğŸ” NÃºmero de tentativas
  default_timeout: 300             # â±ï¸ Timeout padrÃ£o por comando
  log_json: true                   # ğŸ“„ Salvar logs em JSON
  docker_default_tty: true
  docker_default_interactive: false