---
galaxy_info:
  author: Rosthan Pereira
  description: "Role genérica para execução de scripts e comandos em fases (pré-run, run-action, post-run)."
  company: "Nordsh"
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Windows
      versions:
        - all
    - name: EL
      versions:
        - all
dependencies: []
